### ISSUE TITLE
Cool project, gave you a star! (please check this runtime error)

### ISSUE THREAD

**Issue by sympati** [negrel/allelua#1]
First off, it's really a cool idea.

I'm building it on macOS and getting this error, unless I comment out `local buffer = require("string.buffer")` in `allelua/src/bin/allelua/lua/string/string.lua` which defies its purpose:

```shell
cargo b --release
cd target/release/
./allelua run time.lua
runtime error: [string "string"]:2: module 'string.buffer' not found:
	no field package.preload['string.buffer']
	no file './string/buffer.lua'
	no file '/usr/local/Cellar/luajit/HEAD-ec6edc5/share/luajit-2.1.0-beta3/string/buffer.lua'
	no file '/usr/local/share/lua/5.1/string/buffer.lua'
        ...
```

**Comment by negrel** [comment]
Thanks!

Allelua requires a custom build of LuaJIT with LUA 5.2 compat extension, string buffers, ffi extensions enabled and modified LUAI_MAXSTACK and LUAI_MAXCSTACK constants (see https://github.com/negrel/allelua/blob/master/flake.nix#L42C1-L49C15).

By looking at the error it seems you're luajit version doesn't have string.buffer extension enabled

**Comment by sympati** [comment]
**Edit:** My LuaJIT version was indeed a little bit old! A `brew upgrade luajit` did it. Thank you!

Thank you for the quick response. I guessed the error could be related to having installed LuaJIT with homebrew. How would you get Allelua to see a custom version of LuaJIT on macOS? I think one can get mlua to install specific versions of LuaJIT, I just can't remember how and how to point Allelua to it.

**Comment by sympati** [comment]
My LuaJIT version was indeed a little bit old! A `brew upgrade luajit` did it. Thank you!

**Comment by sympati** [comment]
I might as well close the issue as it was resolved. Thank you.

**Comment by negrel** [comment]
> **Edit:** My LuaJIT version was indeed a little bit old! A `brew upgrade luajit` did it. Thank you!
> 
> Thank you for the quick response. I guessed the error could be related to having installed LuaJIT with homebrew. How would you get Allelua to see a custom version of LuaJIT on macOS? I think one can get mlua to install specific versions of LuaJIT, I just can't remember how and how to point Allelua to it.

IMO the best option is to produce a static executable that embeds luajit. I will do it when I will release the first version of allelua.
